name: Publish Python distribution to PyPI

on: push

jobs:
  build:
    uses: JoshTG/polta/.github/workflows/build.yml
  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/polta
    permissions:
      id-token: write
    steps:
      - name: Download the dist
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy
